### PR TITLE
New Tab Button, toggle for drag and drop

### PR DESCRIPTION
**Pull request by dansiej**
Hi,

Thanks for sharing your project, it's been really useful. I made a few changes to suit my own work, and thought I'd offer them back in case anyone wanted them. They're both turned on by constructor arguments that default to false, so won't change any existing code or behaviour. I added a "New tab" tab, like in chrome, which replaces the double-click to add. I also toggled drag and drop off because it didn't suit my application. 

I'm new to javascript, so the code might not be pretty. And I'm no graphic designer so the + icon isn't great either. But see what you think. Happy to take feedback and improve the code.

Cheers,

dansiej

### CODE REVIEW

**Comment by adamschwartz** [comment]
Hey @dansiej I really appreciate your kinds works and the effort you put into this PR.

I’d be happy to accept a PR for a new tab button as long as it looks like the one in Google Chrome.

image

I’d also be happy to accept a PR for an option to disable the drag and drop behavior.

But each of these should be made as separate PRs and try to fit into the existing coding style of the project (as well as general contributing guidelines). For example, you seem to use a convention in which there is a space after left parenthesis in an if block (`if ( foo)`). This was not the convention of the project up until now so you’ll want to remove those. Additionally, e.g. you’d want to remove the lines of commented out code from `setupNewButton`:

image

Thanks again.

**Comment by dansiej** [comment]
Hi Adam,

Thanks for the patient and detailed response. I'll break this up into separate PRs, and address the code style incompatibilities. The new tab button doesn't look like that yet - that was my aim, I just wasn't good enough to get there quickly and settled for something else, since I couldn't justify spending the time at work. I'll see if I can find the time to get it there before making another PR.

Another question - I currently have both flags as separate arguments to the constructor:

`constructor(dragable = true, newButton = false) {`

 I could make it one optional argument:

`constructor(options = {}) {`

and then build the defaults in later, i.e. 

`if (typeof options.dragable === 'undefined' || options.dragable) {`

Do you have a preference?

**Comment by dansiej** [comment]
Seems like there are some other options too. Once can specify no arguments, but then access an "arguments" object anyway, but this would be very unclear in the code, so it seems like a bad idea.

Other two options I've seen are either

`function thing(o = {option1:"boo", option2:"boo2"}) {`

or

`function thing({option1, option2} = {option1:"boo", option2:"boo2"}) {`

both called by `thing({option1:"x", option2:"y"});`, with the first option leading to `o.option1` within the constructor, and the later using `option1` directly. (hope this makes sense), and both still having explicit default arguments. I think I like the last option, but happy to go with whichever you like. Actually, just ran another test, and these options don't work for defining only one optional argument - you would have to either use `undefined` checks, or go back to separate arguments.

Also, what's your target for compatibility? I realised that default parameters are only introduced in ES6, which seems to exclude IE 11 and Android browsers - should I avoid them?

**Comment by adamschwartz** [comment]
Thanks @dansiej. I think my preference regarding defaults would be something like having a `defaultOptions = { ... }` object specified near or at the top of the document, and then use something like `this.options = extend({}, defaultOptions, options)` in which `options` is passed into the constructor and `extend` is a defined helper function.

**Comment by adamschwartz** [comment]
Closing due to inactivity.

**Comment by tiagorangel2011** [comment]
Why not bring this back?

**Pull request closed without merging**
